services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-simple-attendance-pwa}
    container_name: simple-attendance-pwa
    ports:
      - "3131:3131"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: always
